import Link from 'next/link'
import styles from 'styles/index.module.css'
import Head from 'next/head'
import { useTheme } from '@nextui-org/react'
import { CSS, Button, Loading, Input } from '@nextui-org/react'
import { useState, useRef, useEffect, localStorage } from 'react'
import { Router, useRouter } from 'next/router'
import { gql, useMutation } from '@apollo/client'
import client from '../apollo-client'
import { logMissingFieldErrors } from '@apollo/client/core/ObservableQuery'


export default function signIn() {
  const router = useRouter()

  const username = useRef('')
  const password = useRef('')

  const logIn = async function () {
    const mutationQ = gql`
      mutation Mutation($loginInput: LoginInput) {
        loginUser(loginInput: $loginInput) {
          department
          _id
          description
          name
          execs {
            _id
            name
            program
            role
            year
          }
        }
      }
    `

    client
      .mutate({
        mutation: mutationQ,
        variables: {
          loginInput: {
            email: username.current.value,
            password: password.current.value,
          },
        },
      })
      .then((data) => {
        let clubData = data.data.loginUser
        clubData.execs.map((item,index)=>{delete item.__typename;})

        router.push({
          pathname: 'club-landing',
          query: {
            id: clubData._id,
            name: clubData.name,
            department: clubData.department,
            description: clubData.description,
            execs: JSON.stringify(clubData.execs),
          },
        })

      })
      .catch((e) => {
        alert(e.message)
      })
  }

  return (
    <div
      className={styles.body}
      style={{
        background: 'linear-gradient(112deg, #7EE8FA -50%, #EEC0C6 50%)',
      }}
    >
      <Head>
        <title>Welcome to UES Connect</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h1 className="text-5xl mt-16 text-blue-500 ">Club Sign In</h1>

      <div
        style={{ display: 'flex', flexDirection: 'column', marginTop: '50px' }}
      >
        <Input
          ref={username}
          className=" bg-black mb-8"
          color="primary"
          size="xl"
          bordered
          label="Email Address"
        />
        <Input.Password
          ref={password}
          className="bg-black mb-8"
          size="xl"
          color="primary"
          bordered
          label="Password"
        />

        <Button bordered color="primary" onPress={logIn}>
          Log In
        </Button>
      </div>

    </div>
  )
}
